### ISSUE TITLE
Create Utilities not working on server

### ISSUE THREAD

**Issue by JuniorWolfgamingDE** [Duqueeee/create-utilities#1]
Hey! The mod is sadly not working on my server. 

```[17:56:22] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'createutilities'!
	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.28) ~[?:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.21.jar:?]
	at net.minecraft.server.Main.main(Main:101) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.19.2-loader.0.14.21-launcher.0.11.2.jar:0.11.2]
	Suppressed: java.lang.NoClassDefFoundError: net/fabricmc/fabric/impl/blockrenderlayer/BlockRenderLayerMapImpl
		at blackwolf00.moretrapdoor.util.Setup.setupClient(Setup.java:11) ~[MoreTrapdoor-1.19.2-1.0.0-%5BFABRIC%5D.jar:?]
		at blackwolf00.moretrapdoor.Main.onInitialize(Main.java:36) ~[MoreTrapdoor-1.19.2-1.0.0-%5BFABRIC%5D.jar:?]
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.21.jar:?]
		at net.minecraft.server.Main.main(Main:101) [server-intermediary.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.21.jar:?]
		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.21.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.21.jar:?]
		at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.21.jar:?]
		at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.19.2-loader.0.14.21-launcher.0.11.2.jar:0.11.2]
	Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.impl.blockrenderlayer.BlockRenderLayerMapImpl
		at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.21.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
		... 11 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_827
	at me.duquee.createutilities.CreateUtilities.onInitialize(CreateUtilities.java:38) ~[createutilities-0.1.0+1.19.2.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	... 8 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_827
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at me.duquee.createutilities.CreateUtilities.onInitialize(CreateUtilities.java:38) ~[createutilities-0.1.0+1.19.2.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	... 8 more```

**Comment by Duqueeee** [comment]
**Hi there!**

Thank you for bringing the issue to my attention. I'm glad to inform you that the problem has been fixed. You can find the latest version of the mod at the following links:

**CurseForge:** https://curseforge.com/minecraft/mc-mods/create-utilities-fabric/files/4616665
**Modrinth:** https://modrinth.com/mod/create-utilities/version/0.1.1+1.19.2

Additionally, I recommend updating More Beautiful Trapdoors to the latest version as well, as it had a similar issue that has been resolved.

If you have any further questions or need any assistance, please don't hesitate to ask. I'm here to help!

Thank you again for your report and your contribution to the project!
