### ISSUE TITLE
crashing 

### ISSUE THREAD

**Issue by josho2011** [Duqueeee/create-utilities#5]
Crashing cuz this mod it says crash report
-- Head -- 
Thread: Render thread 
Stacktrace:
 
	at com.jozufozu.flywheel.core.PartialModel.<init>(PartialModel.java:31) ~[flywheel-forge-1.19.2-0.6.9-18.jar%23286!/:0.6.9-18] {re:mixin,re:classloading,pl:mixin:APP:railways-common.mixins.json:client.AccessorPartialModel,pl:mixin:A}
 
-- MOD createutilities -- 
Details: 
	Caused by 0: java.lang.ExceptionInInitializerError 
		at me.duquee.createutilities.CreateUtilitiesClient.clientInit(CreateUtilitiesClient.java:17) ~[createutilities-0.1.3+1.19.2.jar%23238!/:1.19.2-0.5.1.c-37-0.1.3] {re:classloading} 
		at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%2385!/:?] {} 
		at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%2385!/:?] {} 
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2385!/:?] {} 
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2385!/:?] {} 
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19.2-43.2.23.jar%23267!/:?] {} 
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:122) ~[fmlcore-1.19.2-43.2.23.jar%23266!/:?] {} 
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {} 
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {} 
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {} 
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {} 
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {} 
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {} 
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
 
 
	Mod File: /C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/com.modrinth.theseus/profiles/create forge/mods/createutilities-0.1.3+1.19.2.jar 
	Failure message: Create Utilities (createutilities) encountered an error during the sided_setup event phase 
		java.lang.ExceptionInInitializerError: null 
	Mod Version: 1.19.2-0.5.1.c-37-0.1.3 
	Mod Issue URL: NOT PROVIDED 
	Exception message: java.lang.RuntimeException: PartialModel 'createutilities:block/void_chest/lid' loaded after ModelEvent.RegisterAdditional 
Stacktrace:
 
	at com.jozufozu.flywheel.core.PartialModel.<init>(PartialModel.java:31) ~[flywheel-forge-1.19.2-0.6.9-18.jar%23286!/:0.6.9-18] {re:mixin,re:classloading,pl:mixin:APP:railways-common.mixins.json:client.AccessorPartialModel,pl:mixin:A}
 
	at me.duquee.createutilities.blocks.CUPartialsModels.block(CUPartialsModels.java:12) ~[createutilities-0.1.3+1.19.2.jar%23238!/:1.19.2-0.5.1.c-37-0.1.3] {re:classloading}
 
	at me.duquee.createutilities.blocks.CUPartialsModels.<clinit>(CUPartialsModels.java:9) ~[createutilities-0.1.3+1.19.2.jar%23238!/:1.19.2-0.5.1.c-37-0.1.3] {re:classloading}
 
	at me.duquee.createutilities.CreateUtilitiesClient.clientInit(CreateUtilitiesClient.java:17) ~[createutilities-0.1.3+1.19.2.jar%23238!/:1.19.2-0.5.1.c-37-0.1.3] {re:classloading}
 
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%2385!/:?] {}
 
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%2385!/:?] {}
 
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2385!/:?] {}
 
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2385!/:?] {}
 
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19.2-43.2.23.jar%23267!/:?] {}
 
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:122) ~[fmlcore-1.19.2-43.2.23.jar%23266!/:?] {}
 
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
 
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
 
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
 
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
 
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
 
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
 
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

**Comment by Duqueeee** [comment]
I can't seem to be able to replicate the crash. Which version of Create do you have installed?

**Comment by cfnnit** [comment]
Here are some people having the same problem with 1.20.1.
But the weird thing is that I don't get the crash, but people who got my modpack do.

![image](https://github.com/Duqueeee/create-utilities/assets/61566693/9a28daa8-38fc-4872-a90a-1e2a5c745ad2)

**Comment by Duqueeee** [comment]
Thank you for bringing this issue to my attention! The problem has been resolved in the latest patch!
